name: 'Workflow Canary'
description: 'split traffic on steps or jobs by proportion!'
inputs:
  percentage:  
    description: 'an integer between 0 and 100, to represent the amount of traffic'
    required: true

outputs:
  canary:
    description: "boolean value indicating whether to proceed"
    value: ${{ steps.tweet.outputs.canary }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: checkout github code
      shell: bash
      run: |
        echo "pwd $(pwd)"
        echo "----"
        ls .

    - name: check canary
      shell: bash
      id: tweet
      run: |
        echo "checking canary"
        echo "percentage: ${{ inputs.percentage }}"
        echo "----"
        RANDOM=$((RANDOM % 100))
        echo "random number: $RANDOM"
        echo "----"

        if [ $RANDOM -lt ${{ inputs.percentage }} ]; then
          echo "we will proceed!"
          CANARY='true'
          echo $CANARY
          echo "canary=$CANARY" >> $GITHUB_OUTPUT
        else
          echo "we will not proceed!"
          CANARY='false'
          echo $CANARY
          echo "canary=$CANARY" >> $GITHUB_OUTPUT
        fi

    - name: echo canary
      run: |
        echo "canary in action: ${{ steps.tweet.outputs.canary }}"